name: nichart
description: >-
  Beautiful, animated, theme-aware charts for Flutter with gorgeous defaults rendered
  with pure Dart on every platform.
version: 1.0.1
repository: https://github.com/ghuyfel/nichart
topics:
  - charts
  - visualization
  - graphs
  - ui
  - widgets

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.18.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  image: ^4.3.0
